name: CI with Codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Codecov가 git history를 필요로 함
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests and generate coverage
      run: |
        echo "JAVA_HOME is: $JAVA_HOME"
        java -version
        ./gradlew test jacocoTestReport --stacktrace --info -Dorg.gradle.java.home="$JAVA_HOME"
      env:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8"
    
    - name: Verify coverage file exists
      run: |
        ls -la build/reports/jacoco/test/
        if [ -f "build/reports/jacoco/test/jacocoTestReport.xml" ]; then
          echo "Coverage file found"
          head -20 build/reports/jacoco/test/jacocoTestReport.xml
        else
          echo "Coverage file not found!"
          exit 1
        fi
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./build/reports/jacoco/test/jacocoTestReport.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true  # 에러 시 실패하도록 변경
        verbose: true
        override_branch: main
        override_commit: ${{ github.sha }}
    
    - name: Upload coverage via curl (fallback)
      if: failure()
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -f build/reports/jacoco/test/jacocoTestReport.xml -t ${{ secrets.CODECOV_TOKEN }}
    
    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          build/reports/tests/
          build/reports/jacoco/
